<?php
	$this->headScript()
		->appendFile("/modules/whiteboard/scripts/tools.js")
		->appendFile("/modules/whiteboard/scripts/managers.js")
		->appendFile("/modules/whiteboard/scripts/app.js");

	$this->headLink(array(
        'rel' => "stylesheet/less",
        'type' => "text/css",
        'href' => "/modules/whiteboard/styles/app.less"
	));
?>
<div id="whiteboard-container" class="page-wrapper"></div>